# Site settings
title:            Welcome to the Long's Homepage!
author:
        name:     Chau Long Do
        email:    dolong2110@gmail.com
twitter_username: Chau Long Do
github_username:  dolong2110
instagram:        chaulong98    
description:      "It's my shelter where I update my profile and projects. I also share my knowlege and experience here. Your visit is one of my passion"
# url is the full website URL
url:              https://dolong2110.github.io/

# Build settings
markdown:         kramdown
theme:            jekyll-theme-architect


# List of links in the navigation bar
navbar-links:
  About Long: "aboutme"
  Education: "education"
  Projects and Skills: "projects skils"
  Open Learning: "openlearning"
  Blog: "blog"
  CV: "cv"
